services:
  - type: web
    name: streamlive
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: RAPIDAPI_KEY
        sync: false
